---
title: Data science in financial sector
author: Fabian Kuyeko
date: '2020-06-05'
slug: data-science-in-financial-sector
categories:
  - Finance
  - Data Sience
tags:
  - Kuyeko
  - Tanzania
  - Finance
  - Data Science
slider: true
# banner: img/indiagate1.jpg
banner: banners/featured-4.jpg
---

The finance sector in Tanza is hampered by the COVID-19......
In the Northeast monsoon season of 2020 the field component of an experiment designed to observe oceanographic parameters began in the Pemba Channel. This campaign was done by team from the Institute of Marine Sciences of the University of Dar es Salaam through the support of SAPPHIRE project.

The field data collection aimed to collect physical and biological data that can later be combined with meteorological and other oceanographic observations acquired through satellite. Once the data processed and compiled will feed into models to improve our understanding of the influence of physical processes in the ocean and its representation in models.

The upper ocean current circulation observations was measured using an ADCP instrument. The dataset that has been gathered far exceeds previous efforts to observe the physical processes anywhere in the ocean, both in its scope and range of techniques deployed. Combined with a comprehensive set of meteorological and air-sea flux measurements, it is giving unprecedented insights into the dynamics and thermodynamics of a closely coupled, semienclosed system known to have direct influence on the processes that control global climate.

